package ru.stqa.java_avi.addressbook.tests;// Generated by Selenium IDE

import org.testng.annotations.Test;
import ru.stqa.java_avi.addressbook.model.ContactData;

public class ContactCreationTests extends TestBase {

  @Test
  public void testContactCreation() {
    app.getNavigationHelper().gotoHomePage();
    app.getContactHelper().initContactCreation();
    app.getContactHelper().fillContactForm(new ContactData("Artur", "Ivanov", "Cherepovets", "+79845612311", "av.ivanov@mail.com"));
    app.getContactHelper().submitContactCreation();
    app.getContactHelper().returnToHomePage();
  }
}
